export interface Phrase {
  ru: string;
  vi: string;
  pron: string;
}

export interface Category {
  id: string;
  title: string;
  icon: string;
  phrases: Phrase[];
}

export interface AlphabetLetter {
  letter: string;
  name: string;
  pron: string;
}

export interface DictionaryEntry {
  ru: string;
  vi: string;
  type: string;
}

export const ALPHABET: AlphabetLetter[] = [
  { letter: "А а", name: "a", pron: "a" },
  { letter: "Б б", name: "be", pron: "bê" },
  { letter: "В в", name: "ve", pron: "vê" },
  { letter: "Г г", name: "ge", pron: "ghê" },
  { letter: "Д д", name: "de", pron: "đê" },
  { letter: "Е е", name: "je", pron: "ye" },
  { letter: "Ё ё", name: "jo", pron: "yo" },
  { letter: "Ж ж", name: "zhe", pron: "giê (uốn lưỡi)" },
  { letter: "З з", name: "ze", pron: "zê" },
  { letter: "И и", name: "i", pron: "i" },
  { letter: "Й й", name: "i kratkoje", pron: "y ngắn" },
  { letter: "К к", name: "ka", pron: "ka" },
  { letter: "Л л", name: "el", pron: "en" },
  { letter: "М м", name: "em", pron: "em" },
  { letter: "Н н", name: "en", pron: "en" },
  { letter: "О о", name: "o", pron: "o" },
  { letter: "П п", name: "pe", pron: "pê" },
  { letter: "Р р", name: "er", pron: "e-rờ (rung)" },
  { letter: "С с", name: "es", pron: "ét" },
  { letter: "Т т", name: "te", pron: "tê" },
  { letter: "У у", name: "u", pron: "u" },
  { letter: "Ф ф", name: "ef", pron: "ép" },
  { letter: "Х х", name: "ha", pron: "kha" },
  { letter: "Ц ц", name: "ce", pron: "txê" },
  { letter: "Ч ч", name: "che", pron: "chê" },
  { letter: "Ш ш", name: "sha", pron: "să (nặng)" },
  { letter: "Щ щ", name: "shcha", pron: "s-tra" },
  { letter: "Ъ ъ", name: "tvyordyj znak", pron: "dấu cứng" },
  { letter: "Ы ы", name: "y", pron: "ư" },
  { letter: "Ь ь", name: "myagkij znak", pron: "dấu mềm" },
  { letter: "Э э", name: "e", pron: "e" },
  { letter: "Ю ю", name: "ju", pron: "yu" },
  { letter: "Я я", name: "ja", pron: "ya" },
];

export const CATEGORIES: Category[] = [
  {
    id: "basic",
    title: "Giao Tiếp Cơ Bản",
    icon: "MessageCircle",
    phrases: [
      { ru: "Здравствуйте", vi: "Xin chào (trang trọng)", pron: "Dơ-rát-vui-che" },
      { ru: "Привет", vi: "Chào (thân mật)", pron: "Pri-viét" },
      { ru: "Как дела?", vi: "Bạn khỏe không?", pron: "Kác đi-la?" },
      { ru: "Хорошо, спасибо", vi: "Tốt, cảm ơn", pron: "Kha-ra-sô, xpa-xi-ba" },
      { ru: "Отлично", vi: "Tuyệt vời", pron: "At-lich-na" },
      { ru: "Как вас зовут?", vi: "Tên bạn là gì? (trang trọng)", pron: "Kác vát za-vút?" },
      { ru: "Меня зовут...", vi: "Tên tôi là...", pron: "Mi-ni-a za-vút..." },
      { ru: "Очень приятно", vi: "Rất vui được gặp bạn", pron: "Ô-chen pri-át-na" },
      { ru: "До свидания", vi: "Tạm biệt", pron: "Đa xvi-đa-ni-ya" },
      { ru: "Пока", vi: "Chào nhé (tạm biệt thân mật)", pron: "Pa-ka" },
      { ru: "Удачи!", vi: "Chúc may mắn!", pron: "U-đa-chi!" },
      { ru: "Да", vi: "Vâng / Có", pron: "Đa" },
      { ru: "Нет", vi: "Không", pron: "Niết" },
      { ru: "Может быть", vi: "Có lẽ", pron: "Mô-zjet bưit" },
    ],
  },
  {
    id: "daily",
    title: "Hàng Ngày",
    icon: "Sun",
    phrases: [
      { ru: "Доброе утро", vi: "Chào buổi sáng", pron: "Đô-brơ-ye út-tra" },
      { ru: "Добрый день", vi: "Chào buổi chiều", pron: "Đô-brưi điên" },
      { ru: "Добрый вечер", vi: "Chào buổi tối", pron: "Đô-brưi viê-cher" },
      { ru: "Спокойной ночи", vi: "Chúc ngủ ngon", pron: "Xpa-kôi-nôi nô-chi" },
      { ru: "Где туалет?", vi: "Nhà vệ sinh ở đâu?", pron: "Gơ-đê tu-a-liết?" },
      { ru: "Здесь есть банкомат?", vi: "Gần đây có ATM không?", pron: "Zđiê-xi iêxt ban-ka-mát?" },
      { ru: "Я không hiểu", vi: "Я не понимаю", pron: "Ya ni pa-ni-ma-yu" },
      { ru: "Вы говорите по-английски?", vi: "Bạn có nói tiếng Anh không?", pron: "Vư ga-va-ri-che pa ang-li-xki?" },
      { ru: "Повторите, пожалуйста", vi: "Làm ơn nhắc lại", pron: "Pa-vta-ri-che pa-za-lu-xta" },
      { ru: "Пишите здесь", vi: "Hãy viết vào đây", pron: "Pi-si-che zđiê-xi" },
    ],
  },
  {
    id: "classroom",
    title: "Lớp Học",
    icon: "BookOpen",
    phrases: [
      { ru: "Урок начинается", vi: "Bài học bắt đầu", pron: "U-rốt na-chi-na-iet-xa" },
      { ru: "Откройте книгу", vi: "Mở sách ra", pron: "At-krôi-che kơ-ni-gu" },
      { ru: "Слушайте и повторяйте", vi: "Nghe và nhắc lại", pron: "Xlu-sai-che i pa-vta-rai-che" },
      { ru: "У вас есть вопросы?", vi: "Bạn có câu hỏi nào không?", pron: "U vát iết va-prô-xư?" },
      { ru: "Я готов / Я готова", vi: "Tôi đã sẵn sàng (nam/nữ)", pron: "Ya ga-tốp / Ya ga-tô-va" },
      { ru: "Домашнее задание", vi: "Bài tập về nhà", pron: "Đa-mas-ni-ye za-đa-ni-ye" },
      { ru: "Слушайте внимательно", vi: "Hãy lắng nghe cẩn thận", pron: "Xlu-sai-che vni-ma-chel-na" },
      { ru: "Переведите это", vi: "Hãy dịch câu này", pron: "Pi-ri-vi-đi-che ê-ta" },
    ],
  },
  {
    id: "kitchen",
    title: "Nhà Ăn / Bếp Ăn",
    icon: "Utensils",
    phrases: [
      { ru: "Я хочу есть", vi: "Tôi muốn ăn", pron: "Ya kha-chu iêxt" },
      { ru: "Приятного аппетита", vi: "Chúc ngon miệng", pron: "Pri-at-na-va a-pi-ti-ta" },
      { ru: "Принесите счет, пожалуйста", vi: "Làm ơn mang hóa đơn cho tôi", pron: "Pri-ni-xi-che si-ốt pa-za-lu-xta" },
      { ru: "Чай или кофе?", vi: "Trà hay cà phê?", pron: "Chai i-li kô-phê?" },
      { ru: "Я вегетарианец", vi: "Tôi ăn chay", pron: "Ya vi-ghi-ta-ri-an-niê-tx" },
      { ru: "С сахаром / Без сахара", vi: "Có đường / Không đường", pron: "X xáp-kha-rơm / Biêz xáp-kha-ra" },
      { ru: "Вкусно", vi: "Ngon", pron: "Vơ-kút-na" },
      { ru: "Передай соль, пожалуйста", vi: "Làm ơn đưa muối giúp tôi", pron: "Pi-ri-đai xôl pa-za-lu-xta" },
      { ru: "Вода", vi: "Nước", pron: "Va-đa" },
      { ru: "Хлеб", vi: "Bánh mì", pron: "Khơ-liêp" },
    ],
  },
  {
    id: "shopping",
    title: "Mua Sắm / Đi Chợ",
    icon: "ShoppingCart",
    phrases: [
      { ru: "Сколько это стоит?", vi: "Cái này giá bao nhiêu?", pron: "Xkôn-ka ê-ta xtô-ít?" },
      { ru: "Это слишком дорого", vi: "Cái này quá đắt", pron: "Ê-ta xli-xkơm đô-ra-ga" },
      { ru: "Можно скидку?", vi: "Có thể giảm giá không?", pron: "Mô-zna xkít-ku?" },
      { ru: "Я куплю это", vi: "Tôi sẽ mua nó", pron: "Ya ku-pli-u ê-ta" },
      { ru: "Пакет нужен?", vi: "Bạn có cần túi không?", pron: "Pa-kiết nu-zên?" },
      { ru: "Где примерочная?", vi: "Phòng thay đồ ở đâu?", pron: "Gơ-đê pri-miê-rát-na-ya?" },
      { ru: "Картой или наличными?", vi: "Bằng thẻ hay tiền mặt?", pron: "Các-tôi i-li na-li-chnư-mi?" },
    ],
  },
  {
    id: "help",
    title: "Nhờ Vả / Giúp Đỡ",
    icon: "HandHelping",
    phrases: [
      { ru: "Помогите мне, пожалуйста", vi: "Làm ơn giúp tôi", pron: "Pa-ma-ghi-che mniê pa-za-lu-xta" },
      { ru: "Вы можете мне помочь?", vi: "Bạn có thể giúp tôi không?", pron: "Vư mô-ze-che mniê pa-môch?" },
      { ru: "Вызовите полицию", vi: "Hãy gọi cảnh sát", pron: "Vư-za-vi-che pa-li-txi-iu" },
      { ru: "Осторожно!", vi: "Cẩn thận!", pron: "A-xta-rô-zna!" },
      { ru: "Вызовите врача", vi: "Hãy gọi bác sĩ", pron: "Vư-za-vi-che vra-cha" },
      { ru: "Я потерял телефон", vi: "Tôi bị mất điện thoại", pron: "Ya pa-ti-ri-al chi-li-phôn" },
      { ru: "Я потерялся / Я потерялась", vi: "Tôi bị lạc (nam/nữ)", pron: "Ya pa-ti-ri-al-xa / Ya pa-ti-ri-alát-xa" },
    ],
  },
  {
    id: "thanks",
    title: "Cảm Ơn / Đáp Lại",
    icon: "Heart",
    phrases: [
      { ru: "Спасибо большое", vi: "Cảm ơn rất nhiều", pron: "Xpa-xi-ba bal-sôi" },
      { ru: "Пожалуйста", vi: "Làm ơn / Không có gì", pron: "Pa-za-lu-xta" },
      { ru: "Не за что", vi: "Không có gì (đáp lại lời cảm ơn)", pron: "Niê za xtô" },
      { ru: "Я вам очень благодарен", vi: "Tôi rất biết ơn bạn", pron: "Ya vam ô-chen bla-ga-đa-riên" },
      { ru: "Благодарю вас", vi: "Cảm tạ bạn", pron: "Bla-ga-đa-ri-u vát" },
    ],
  },
  {
    id: "tech",
    title: "CNTT & An Ninh",
    icon: "ShieldCheck",
    phrases: [
      { ru: "Информационная безопасность", vi: "An toàn thông tin", pron: "In-pôr-ma-txi-ôn-na-ya biê-za-pát-nớt" },
      { ru: "Кибербезопасность", vi: "An ninh mạng", pron: "Ki-biêr-biê-za-pát-nớt" },
      { ru: "Компьютер", vi: "Máy tính", pron: "Kam-pút-tiêr" },
      { ru: "Сеть", vi: "Mạng", pron: "Xiết" },
      { ru: "Пароль", vi: "Mật mã", pron: "Pa-rôl" },
      { ru: "Шифрование", vi: "Mã hóa", pron: "Si-phrô-va-ni-ye" },
      { ru: "Уязвимость", vi: "Lỗ hổng bảo mật", pron: "U-ya-zvi-môxt" },
      { ru: "База данных", vi: "Cơ sở dữ liệu", pron: "Ba-za đa-nnưkh" },
      { ru: "Сервер", vi: "Máy chủ", pron: "Xiêr-viêr" },
      { ru: "Программное обеспечение", vi: "Phần mềm", pron: "Pra-gram-na-ye a-biê-xpiê-chi-ni-ye" },
      { ru: "Взлом", vi: "Hack / Xâm nhập", pron: "Vơ-zlôm" },
      { ru: "Защита данных", vi: "Bảo vệ dữ liệu", pron: "Za-txit-ta đa-nnưkh" },
      { ru: "Вирус", vi: "Vi-rút", pron: "Vi-rut" },
    ],
  },
];

export const DICTIONARY: DictionaryEntry[] = [
  { ru: "Человек", vi: "Con người", type: "Danh từ" },
  { ru: "Друг", vi: "Bạn bè", type: "Danh từ" },
  { ru: "Работа", vi: "Công việc", type: "Danh từ" },
  { ru: "Деньги", vi: "Tiền bạc", type: "Danh từ" },
  { ru: "Время", vi: "Thời gian", type: "Danh từ" },
  { ru: "Жизнь", vi: "Cuộc sống", type: "Danh từ" },
  { ru: "Мир", vi: "Thế giới / Hòa bình", type: "Danh từ" },
  { ru: "Город", vi: "Thành phố", type: "Danh từ" },
  { ru: "Страна", vi: "Quốc gia", type: "Danh từ" },
  { ru: "Семья", vi: "Gia đình", type: "Danh từ" },
  { ru: "Дом", vi: "Nhà", type: "Danh từ" },
  { ru: "Еда", vi: "Đồ ăn", type: "Danh từ" },
  { ru: "Вода", vi: "Nước", type: "Danh từ" },
  { ru: "Большой", vi: "Lớn", type: "Tính từ" },
  { ru: "Маленький", vi: "Nhỏ", type: "Tính từ" },
  { ru: "Хороший", vi: "Tốt", type: "Tính từ" },
  { ru: "Плохой", vi: "Tồi tệ", type: "Tính từ" },
  { ru: "Красивый", vi: "Đẹp", type: "Tính từ" },
  { ru: "Новый", vi: "Mới", type: "Tính từ" },
  { ru: "Старый", vi: "Cũ", type: "Tính từ" },
  { ru: "Идти", vi: "Đi bộ", type: "Động từ" },
  { ru: "Делать", vi: "Làm", type: "Động từ" },
  { ru: "Знать", vi: "Biết", type: "Động từ" },
  { ru: "Видеть", vi: "Nhìn thấy", type: "Động từ" },
  { ru: "Слышать", vi: "Nghe thấy", type: "Động từ" },
  { ru: "Говорить", vi: "Nói", type: "Động từ" },
  { ru: "Хотеть", vi: "Muốn", type: "Động từ" },
  { ru: "Думать", vi: "Nghĩ", type: "Động từ" },
  { ru: "Компьютер", vi: "Máy tính", type: "CNTT" },
  { ru: "Данные", vi: "Dữ liệu", type: "CNTT" },
  { ru: "Система", vi: "Hệ thống", type: "CNTT" },
  { ru: "Протокол", vi: "Giao thức", type: "CNTT" },
  { ru: "Ключ", vi: "Chìa khóa / Khóa", type: "CNTT" },
  { ru: "Доступ", vi: "Truy cập", type: "CNTT" },
  { ru: "Ошибка", vi: "Lỗi", type: "CNTT" },
  { ru: "Файл", vi: "Tập tin", type: "CNTT" },
  { ru: "Сайт", vi: "Trang web", type: "CNTT" },
  { ru: "Сегодня", vi: "Hôm nay", type: "Trạng từ" },
  { ru: "Завтра", vi: "Ngày mai", type: "Trạng từ" },
  { ru: "Вчера", vi: "Hôm qua", type: "Trạng từ" },
  { ru: "Здесь", vi: "Ở đây", type: "Trạng từ" },
  { ru: "Там", vi: "Ở kia", type: "Trạng từ" },
  { ru: "Сейчас", vi: "Bây giờ", type: "Trạng từ" },
  { ru: "Никогда", vi: "Không bao giờ", type: "Trạng từ" },
  { ru: "Огромный", vi: "Khổng lồ", type: "Tính từ" },
  { ru: "Безопасный", vi: "An toàn", type: "Tính từ" },
  { ru: "Опасный", vi: "Nguy hiểm", type: "Tính từ" },
  { ru: "Быстрый", vi: "Nhanh", type: "Tính từ" },
  { ru: "Медленный", vi: "Chậm", type: "Tính từ" },
  { ru: "Умный", vi: "Thông minh", type: "Tính từ" },
  { ru: "Билет", vi: "Vé", type: "Danh từ" },
  { ru: "Самолёт", vi: "Máy bay", type: "Danh từ" },
  { ru: "Поезд", vi: "Tàu hỏa", type: "Danh từ" },
  { ru: "Метро", vi: "Tàu điện ngầm", type: "Danh từ" },
  { ru: "Книга", vi: "Sách", type: "Danh từ" },
  { ru: "Ручка", vi: "Bút", type: "Danh từ" },
  { ru: "Тетрадь", vi: "Vở", type: "Danh từ" },
  { ru: "Школа", vi: "Trường học", type: "Danh từ" },
  { ru: "Ученик", vi: "Học sinh", type: "Danh từ" },
  { ru: "Учитель", vi: "Giáo viên", type: "Danh từ" },
  { ru: "Студент", vi: "Sinh viên", type: "Danh từ" },
  { ru: "Россия", vi: "Nước Nga", type: "Danh từ" },
  { ru: "Вьетнам", vi: "Việt Nam", type: "Danh từ" },
  { ru: "Язык", vi: "Ngôn ngữ", type: "Danh từ" },
  { ru: "Слово", vi: "Từ ngữ", type: "Danh từ" },
  { ru: "Погода", vi: "Thời tiết", type: "Danh từ" },
  { ru: "Солнце", vi: "Mặt trời", type: "Danh từ" },
  { ru: "Небо", vi: "Bầu trời", type: "Danh từ" },
  { ru: "Море", vi: "Biển", type: "Danh từ" },
  { ru: "Река", vi: "Sông", type: "Danh từ" },
  { ru: "Лес", vi: "Rừng", type: "Danh từ" },
  { ru: "Гора", vi: "Núi", type: "Danh từ" },
  { ru: "Собака", vi: "Con chó", type: "Danh từ" },
  { ru: "Кошка", vi: "Con mèo", type: "Danh từ" },
  { ru: "Машина", vi: "Ô tô", type: "Danh từ" },
  { ru: "Автобус", vi: "Xe buýt", type: "Danh từ" },
  { ru: "Хлеб", vi: "Bánh mì", type: "Thực phẩm" },
  { ru: "Молоко", vi: "Sữa", type: "Thực phẩm" },
  { ru: "Мясо", vi: "Thịt", type: "Thực phẩm" },
  { ru: "Яблоко", vi: "Quả táo", type: "Thực phẩm" },
  { ru: "Банан", vi: "Quả chuối", type: "Thực phẩm" },
  { ru: "Суп", vi: "Súp", type: "Thực phẩm" },
  { ru: "Алгоритм", vi: "Thuật toán", type: "CNTT" },
  { ru: "Пользователь", vi: "Người dùng", type: "CNTT" },
  { ru: "Интерфейс", vi: "Giao diện", type: "CNTT" },
  { ru: "Процессор", vi: "Bộ vi xử lý", type: "CNTT" },
  { ru: "Анализ", vi: "Phân tích", type: "CNTT" },
  { ru: "Трафик", vi: "Lưu lượng mạng", type: "CNTT" },
  { ru: "Сложный", vi: "Phức tạp", type: "Tính từ" },
  { ru: "Простой", vi: "Đơn giản", type: "Tính từ" },
  { ru: "Интересный", vi: "Thú vị", type: "Tính từ" },
  { ru: "Важный", vi: "Quan trọng", type: "Tính từ" },
  { ru: "Чистый", vi: "Sạch", type: "Tính từ" },
  { ru: "Грязный", vi: "Bẩn", type: "Tính từ" },
];
