export interface Phrase {
  ru: string;
  vi: string;
  pron: string;
}

export interface Category {
  id: string;
  title: string;
  icon: string;
  phrases: Phrase[];
}

export interface AlphabetLetter {
  letter: string;
  name: string;
  pron: string;
}

export interface DictionaryEntry {
  ru: string;
  vi: string;
  pron: string;
  type: string;
}

export const ALPHABET: AlphabetLetter[] = [
  { letter: "А а", name: "a", pron: "a" },
  { letter: "Б б", name: "be", pron: "bê" },
  { letter: "В в", name: "ve", pron: "vê" },
  { letter: "Г г", name: "ge", pron: "ghê" },
  { letter: "Д д", name: "de", pron: "đê" },
  { letter: "Е е", name: "je", pron: "ye" },
  { letter: "Ё ё", name: "jo", pron: "yo" },
  { letter: "Ж ж", name: "zhe", pron: "giê (uốn lưỡi)" },
  { letter: "З з", name: "ze", pron: "zê" },
  { letter: "И и", name: "i", pron: "i" },
  { letter: "Й й", name: "i kratkoje", pron: "y ngắn" },
  { letter: "К к", name: "ka", pron: "ka" },
  { letter: "Л л", name: "el", pron: "en" },
  { letter: "М м", name: "em", pron: "em" },
  { letter: "Н н", name: "en", pron: "en" },
  { letter: "О о", name: "o", pron: "o" },
  { letter: "П п", name: "pe", pron: "pê" },
  { letter: "Р р", name: "er", pron: "e-rờ (rung)" },
  { letter: "С с", name: "es", pron: "ét" },
  { letter: "Т т", name: "te", pron: "tê" },
  { letter: "У у", name: "u", pron: "u" },
  { letter: "Ф ф", name: "ef", pron: "ép" },
  { letter: "Х х", name: "ha", pron: "kha" },
  { letter: "Ц ц", name: "ce", pron: "txê" },
  { letter: "Ч ч", name: "che", pron: "chê" },
  { letter: "Ш ш", name: "sha", pron: "să (nặng)" },
  { letter: "Щ щ", name: "shcha", pron: "s-tra" },
  { letter: "Ъ ъ", name: "tvyordyj znak", pron: "dấu cứng" },
  { letter: "Ы ы", name: "y", pron: "ư" },
  { letter: "Ь ь", name: "myagkij znak", pron: "dấu mềm" },
  { letter: "Э э", name: "e", pron: "e" },
  { letter: "Ю ю", name: "ju", pron: "yu" },
  { letter: "Я я", name: "ja", pron: "ya" },
];

export const CATEGORIES: Category[] = [
  {
    id: "basic",
    title: "Giao Tiếp Cơ Bản",
    icon: "MessageCircle",
    phrases: [
      { ru: "Здравствуйте", vi: "Xin chào (trang trọng)", pron: "Dơ-rát-vui-che" },
      { ru: "Привет", vi: "Chào (thân mật)", pron: "Pri-viét" },
      { ru: "Как дела?", vi: "Bạn khỏe không?", pron: "Kác đi-la?" },
      { ru: "Хорошо, спасибо", vi: "Tốt, cảm ơn", pron: "Kha-ra-sô, xpa-xi-ba" },
      { ru: "Отлично", vi: "Tuyệt vời", pron: "At-lich-na" },
      { ru: "Как вас зовут?", vi: "Tên bạn là gì? (trang trọng)", pron: "Kác vát za-vút?" },
      { ru: "Меня зовут...", vi: "Tên tôi là...", pron: "Mi-ni-a za-vút..." },
      { ru: "Очень приятно", vi: "Rất vui được gặp bạn", pron: "Ô-chen pri-át-na" },
      { ru: "До свидания", vi: "Tạm biệt", pron: "Đa xvi-đa-ni-ya" },
      { ru: "Пока", vi: "Chào nhé (tạm biệt thân mật)", pron: "Pa-ka" },
      { ru: "Удачи!", vi: "Chúc may mắn!", pron: "U-đa-chi!" },
      { ru: "Да", vi: "Vâng / Có", pron: "Đa" },
      { ru: "Нет", vi: "Không", pron: "Niết" },
      { ru: "Может быть", vi: "Có lẽ", pron: "Mô-zjet bưit" },
    ],
  },
  {
    id: "daily",
    title: "Hàng Ngày",
    icon: "Sun",
    phrases: [
      { ru: "Доброе утро", vi: "Chào buổi sáng", pron: "Đô-brơ-ye út-tra" },
      { ru: "Добрый день", vi: "Chào buổi chiều", pron: "Đô-brưi điên" },
      { ru: "Добрый вечер", vi: "Chào buổi tối", pron: "Đô-brưi viê-cher" },
      { ru: "Спокойной ночи", vi: "Chúc ngủ ngon", pron: "Xpa-kôi-nôi nô-chi" },
      { ru: "Где туалет?", vi: "Nhà vệ sinh ở đâu?", pron: "Gơ-đê tu-a-liết?" },
      { ru: "Здесь есть банкомат?", vi: "Gần đây có ATM không?", pron: "Zđiê-xi iêxt ban-ka-mát?" },
      { ru: "Я không hiểu", vi: "Я не понимаю", pron: "Ya ni pa-ni-ma-yu" },
      { ru: "Вы говорите по-английски?", vi: "Bạn có nói tiếng Anh không?", pron: "Vư ga-va-ri-che pa ang-li-xki?" },
      { ru: "Повторите, пожалуйста", vi: "Làm ơn nhắc lại", pron: "Pa-vta-ri-che pa-za-lu-xta" },
      { ru: "Пишите здесь", vi: "Hãy viết vào đây", pron: "Pi-si-che zđiê-xi" },
    ],
  },
  {
    id: "classroom",
    title: "Lớp Học",
    icon: "BookOpen",
    phrases: [
      { ru: "Урок начинается", vi: "Bài học bắt đầu", pron: "U-rốt na-chi-na-iet-xa" },
      { ru: "Откройте книгу", vi: "Mở sách ra", pron: "At-krôi-che kơ-ni-gu" },
      { ru: "Слушайте и повторяйте", vi: "Nghe và nhắc lại", pron: "Xlu-sai-che i pa-vta-rai-che" },
      { ru: "У вас есть вопросы?", vi: "Bạn có câu hỏi nào không?", pron: "U vát iết va-prô-xư?" },
      { ru: "Я готов / Я готова", vi: "Tôi đã sẵn sàng (nam/nữ)", pron: "Ya ga-tốp / Ya ga-tô-va" },
      { ru: "Домашнее задание", vi: "Bài tập về nhà", pron: "Đa-mas-ni-ye za-đa-ni-ye" },
      { ru: "Слушайте внимательно", vi: "Hãy lắng nghe cẩn thận", pron: "Xlu-sai-che vni-ma-chel-na" },
      { ru: "Переведите это", vi: "Hãy dịch câu này", pron: "Pi-ri-vi-đi-che ê-ta" },
    ],
  },
  {
    id: "kitchen",
    title: "Nhà Ăn / Bếp Ăn",
    icon: "Utensils",
    phrases: [
      { ru: "Я хочу есть", vi: "Tôi muốn ăn", pron: "Ya kha-chu iêxt" },
      { ru: "Приятного аппетита", vi: "Chúc ngon miệng", pron: "Pri-at-na-va a-pi-ti-ta" },
      { ru: "Принесите счет, пожалуйста", vi: "Làm ơn mang hóa đơn cho tôi", pron: "Pri-ni-xi-che si-ốt pa-za-lu-xta" },
      { ru: "Чай или кофе?", vi: "Trà hay cà phê?", pron: "Chai i-li kô-phê?" },
      { ru: "Я вегетарианец", vi: "Tôi ăn chay", pron: "Ya vi-ghi-ta-ri-an-niê-tx" },
      { ru: "С сахаром / Без сахара", vi: "Có đường / Không đường", pron: "X xáp-kha-rơm / Biêz xáp-kha-ra" },
      { ru: "Вкусно", vi: "Ngon", pron: "Vơ-kút-na" },
      { ru: "Передай соль, пожалуйста", vi: "Làm ơn đưa muối giúp tôi", pron: "Pi-ri-đai xôl pa-za-lu-xta" },
      { ru: "Вода", vi: "Nước", pron: "Va-đa" },
      { ru: "Хлеб", vi: "Bánh mì", pron: "Khơ-liêp" },
    ],
  },
  {
    id: "shopping",
    title: "Mua Sắm / Đi Chợ",
    icon: "ShoppingCart",
    phrases: [
      { ru: "Сколько это стоит?", vi: "Cái này giá bao nhiêu?", pron: "Xkôn-ka ê-ta xtô-ít?" },
      { ru: "Это слишком дорого", vi: "Cái này quá đắt", pron: "Ê-ta xli-xkơm đô-ra-ga" },
      { ru: "Можно скидку?", vi: "Có thể giảm giá không?", pron: "Mô-zna xkít-ku?" },
      { ru: "Я куплю это", vi: "Tôi sẽ mua nó", pron: "Ya ku-pli-u ê-ta" },
      { ru: "Пакет нужен?", vi: "Bạn có cần túi không?", pron: "Pa-kiết nu-zên?" },
      { ru: "Где примерочная?", vi: "Phòng thay đồ ở đâu?", pron: "Gơ-đê pri-miê-rát-na-ya?" },
      { ru: "Картой или наличными?", vi: "Bằng thẻ hay tiền mặt?", pron: "Các-tôi i-li na-li-chnư-mi?" },
    ],
  },
  {
    id: "help",
    title: "Nhờ Vả / Giúp Đỡ",
    icon: "HandHelping",
    phrases: [
      { ru: "Помогите мне, пожалуйста", vi: "Làm ơn giúp tôi", pron: "Pa-ma-ghi-che mniê pa-za-lu-xta" },
      { ru: "Вы можете мне помочь?", vi: "Bạn có thể giúp tôi không?", pron: "Vư mô-ze-che mniê pa-môch?" },
      { ru: "Вызовите полицию", vi: "Hãy gọi cảnh sát", pron: "Vư-za-vi-che pa-li-txi-iu" },
      { ru: "Осторожно!", vi: "Cẩn thận!", pron: "A-xta-rô-zna!" },
      { ru: "Вызовите врача", vi: "Hãy gọi bác sĩ", pron: "Vư-za-vi-che vra-cha" },
      { ru: "Я потерял телефон", vi: "Tôi bị mất điện thoại", pron: "Ya pa-ti-ri-al chi-li-phôn" },
      { ru: "Я потерялся / Я потерялась", vi: "Tôi bị lạc (nam/nữ)", pron: "Ya pa-ti-ri-al-xa / Ya pa-ti-ri-alát-xa" },
    ],
  },
  {
    id: "thanks",
    title: "Cảm Ơn / Đáp Lại",
    icon: "Heart",
    phrases: [
      { ru: "Спасибо большое", vi: "Cảm ơn rất nhiều", pron: "Xpa-xi-ba bal-sôi" },
      { ru: "Пожалуйста", vi: "Làm ơn / Không có gì", pron: "Pa-za-lu-xta" },
      { ru: "Не за что", vi: "Không có gì (đáp lại lời cảm ơn)", pron: "Niê za xtô" },
      { ru: "Я вам очень благодарен", vi: "Tôi rất biết ơn bạn", pron: "Ya vam ô-chen bla-ga-đa-riên" },
      { ru: "Благодарю вас", vi: "Cảm tạ bạn", pron: "Bla-ga-đa-ri-u vát" },
    ],
  },
  {
    id: "tech",
    title: "CNTT & An Ninh",
    icon: "ShieldCheck",
    phrases: [
      { ru: "Информационная безопасность", vi: "An toàn thông tin", pron: "In-pôr-ma-txi-ôn-na-ya biê-za-pát-nớt" },
      { ru: "Кибербезопасность", vi: "An ninh mạng", pron: "Ki-biêr-biê-za-pát-nớt" },
      { ru: "Компьютер", vi: "Máy tính", pron: "Kam-pút-tiêr" },
      { ru: "Сеть", vi: "Mạng", pron: "Xiết" },
      { ru: "Пароль", vi: "Mật mã", pron: "Pa-rôl" },
      { ru: "Шифрование", vi: "Mã hóa", pron: "Si-phrô-va-ni-ye" },
      { ru: "Уязвимость", vi: "Lỗ hổng bảo mật", pron: "U-ya-zvi-môxt" },
      { ru: "База данных", vi: "Cơ sở dữ liệu", pron: "Ba-za đa-nnưkh" },
      { ru: "Сервер", vi: "Máy chủ", pron: "Xiêr-viêr" },
      { ru: "Программное обеспечение", vi: "Phần mềm", pron: "Pra-gram-na-ye a-biê-xpiê-chi-ni-ye" },
      { ru: "Взлом", vi: "Hack / Xâm nhập", pron: "Vơ-zlôm" },
      { ru: "Защита данных", vi: "Bảo vệ dữ liệu", pron: "Za-txit-ta đa-nnưkh" },
      { ru: "Вирус", vi: "Vi-rút", pron: "Vi-rut" },
    ],
  },
  {
    id: "numbers",
    title: "Số Đếm",
    icon: "Hash",
    phrases: [
      { ru: "Один", vi: "Một", pron: "A-đin" },
      { ru: "Два", vi: "Hai", pron: "Đơ-va" },
      { ru: "Три", vi: "Ba", pron: "Tơ-ri" },
      { ru: "Четыре", vi: "Bốn", pron: "Chi-tư-ri" },
      { ru: "Пять", vi: "Năm", pron: "Pi-át" },
      { ru: "Шесть", vi: "Sáu", pron: "Siêst" },
      { ru: "Семь", vi: "Bảy", pron: "Xiêm" },
      { ru: "Восемь", vi: "Tám", pron: "Vô-xiêm" },
      { ru: "Девять", vi: "Chín", pron: "Điê-vi-át" },
      { ru: "Десять", vi: "Mười", pron: "Điê-xi-át" },
      { ru: "Сто", vi: "Một trăm", pron: "Xtô" },
      { ru: "Тысяча", vi: "Một nghìn", pron: "Tư-xi-cha" },
    ],
  },
  {
    id: "direction",
    title: "Chỉ Đường",
    icon: "Navigation",
    phrases: [
      { ru: "Где находится...?", vi: "...nằm ở đâu?", pron: "Gơ-đê na-kho-đit-xa...?" },
      { ru: "Идите прямо", vi: "Đi thẳng", pron: "I-đi-che pri-a-ma" },
      { ru: "Поверните направо", vi: "Rẽ phải", pron: "Pa-viêr-ni-che na-pra-va" },
      { ru: "Поверните налево", vi: "Rẽ trái", pron: "Pa-viêr-ni-che na-liê-va" },
      { ru: "Остановитесь здесь", vi: "Dừng lại ở đây", pron: "A-xta-na-vi-chiê-xi zđiê-xi" },
      { ru: "Карта", vi: "Bản đồ", pron: "Các-ta" },
      { ru: "Далеко / Близко", vi: "Xa / Gần", pron: "Đa-li-kô / Bơ-li-zka" },
    ],
  },
  {
    id: "emergency",
    title: "Khẩn Cấp",
    icon: "AlertTriangle",
    phrases: [
      { ru: "Помогите!", vi: "Giúp tôi với!", pron: "Pa-ma-ghi-che!" },
      { ru: "Вызовите скорую", vi: "Gọi cấp cứu", pron: "Vư-za-vi-che xkô-ru-iu" },
      { ru: "Я болен / Я больна", vi: "Tôi bị ốm (nam/nữ)", pron: "Ya bô-liên / Ya bal-na" },
      { ru: "У меня болит здесь", vi: "Tôi bị đau ở đây", pron: "U mi-ni-a ba-lít zđiê-xi" },
      { ru: "Где ближайшая аптека?", vi: "Hiệu thuốc gần nhất ở đâu?", pron: "Gơ-đê bơ-li-zai-sai-a ap-tiê-ka?" },
      { ru: "Это срочно!", vi: "Việc này khẩn cấp!", pron: "Ê-ta xrô-chna!" },
    ],
  },
  {
    id: "airport",
    title: "Sân Bay",
    icon: "Plane",
    phrases: [
      { ru: "Где регистрация?", vi: "Quầy làm thủ tục ở đâu?", pron: "Gơ-đê ri-ghi-xtra-txi-ya?" },
      { ru: "Ваш паспорт, пожалуйста", vi: "Làm ơn cho xem hộ chiếu", pron: "Vát pát-pôrt pa-za-lu-xta" },
      { ru: "Где выход на посадку?", vi: "Cửa lên máy bay ở đâu?", pron: "Gơ-đê vư-khốt na pa-xát-ku?" },
      { ru: "У меня пересадка", vi: "Tôi có chuyến bay nối chuyến", pron: "U mi-ni-a pi-ri-xát-ka" },
      { ru: "Мой багаж потерян", vi: "Hành lý của tôi bị thất lạc", pron: "Môi ba-gát pa-tiê-riên" },
    ],
  },
  {
    id: "hotel",
    title: "Khách Sạn",
    icon: "Hotel",
    phrases: [
      { ru: "Я забронировал номер", vi: "Tôi đã đặt phòng trước", pron: "Ya za-bra-ni-rô-val nô-miêr" },
      { ru: "Во сколько завтрак?", vi: "Bữa sáng lúc mấy giờ?", pron: "Va xkôl-ka zát-vơ-răk?" },
      { ru: "Нужен Wi-Fi пароль", vi: "Cần mật khẩu Wi-Fi", pron: "Nu-zên Wi-Fi pa-rôl" },
      { ru: "В номере нет воды", vi: "Trong phòng không có nước", pron: "V nô-miê-ri niết va-đưi" },
      { ru: "Можно выехать позже?", vi: "Có thể trả phòng muộn không?", pron: "Mô-zna vư-ye-khal pô-zje?" },
    ],
  },
];

export const DICTIONARY: DictionaryEntry[] = [
  { ru: "Человек", vi: "Con người", pron: "Chi-la-viếk", type: "Danh từ" },
  { ru: "Друг", vi: "Bạn bè", pron: "Đơ-rúc", type: "Danh từ" },
  { ru: "Работа", vi: "Công việc", pron: "Ra-bô-ta", type: "Danh từ" },
  { ru: "Деньги", vi: "Tiền bạc", pron: "Điên-ghi", type: "Danh từ" },
  { ru: "Время", vi: "Thời gian", pron: "Vơ-riê-mi-ya", type: "Danh từ" },
  { ru: "Жизнь", vi: "Cuộc sống", pron: "Zizn", type: "Danh từ" },
  { ru: "Мир", vi: "Thế giới / Hòa bình", pron: "Mir", type: "Danh từ" },
  { ru: "Город", vi: "Thành phố", pron: "Gô-rớt", type: "Danh từ" },
  { ru: "Страна", vi: "Quốc gia", pron: "Xơ-tra-na", type: "Danh từ" },
  { ru: "Семья", vi: "Gia đình", pron: "Xiêm-ya", type: "Danh từ" },
  { ru: "Дом", vi: "Nhà", pron: "Đôm", type: "Danh từ" },
  { ru: "Еда", vi: "Đồ ăn", pron: "I-đa", type: "Danh từ" },
  { ru: "Вода", vi: "Nước", pron: "Va-đa", type: "Danh từ" },
  { ru: "Большой", vi: "Lớn", pron: "Bal-sôi", type: "Tính từ" },
  { ru: "Маленький", vi: "Nhỏ", pron: "Ma-liên-ki", type: "Tính từ" },
  { ru: "Хороший", vi: "Tốt", pron: "Kha-rô-si", type: "Tính từ" },
  { ru: "Плохой", vi: "Tồi tệ", pron: "Pla-khôi", type: "Tính từ" },
  { ru: "Красивый", vi: "Đẹp", pron: "Kra-xi-vưi", type: "Tính từ" },
  { ru: "Новый", vi: "Mới", pron: "Nô-vưi", type: "Tính từ" },
  { ru: "Старый", vi: "Cũ", pron: "Xta-rưi", type: "Tính từ" },
  { ru: "Идти", vi: "Đi bộ", pron: "It-ti", type: "Động từ" },
  { ru: "Делать", vi: "Làm", pron: "Điê-lat", type: "Động từ" },
  { ru: "Знать", vi: "Biết", pron: "Zơ-nat", type: "Động từ" },
  { ru: "Видеть", vi: "Nhìn thấy", pron: "Vi-điêt", type: "Động từ" },
  { ru: "Слышать", vi: "Nghe thấy", pron: "Xlư-sat", type: "Động từ" },
  { ru: "Говорить", vi: "Nói", pron: "Ga-va-rit", type: "Động từ" },
  { ru: "Хотеть", vi: "Muốn", pron: "Kha-chiết", type: "Động từ" },
  { ru: "Думать", vi: "Nghi", pron: "Đu-mat", type: "Động từ" },
  { ru: "Компьютер", vi: "Máy tính", pron: "Kam-pút-tiêr", type: "CNTT" },
  { ru: "Данные", vi: "Dữ liệu", pron: "Đan-nư-ye", type: "CNTT" },
  { ru: "Система", vi: "Hệ thống", pron: "Xi-xtiê-ma", type: "CNTT" },
  { ru: "Протокол", vi: "Giao thức", pron: "Pra-ta-kôl", type: "CNTT" },
  { ru: "Ключ", vi: "Chìa khóa / Khóa", pron: "Kơ-lúch", type: "CNTT" },
  { ru: "Доступ", vi: "Truy cập", pron: "Đô-xtup", type: "CNTT" },
  { ru: "Ошибка", vi: "Lỗi", pron: "A-sip-ka", type: "CNTT" },
  { ru: "Файл", vi: "Tập tin", pron: "Phail", type: "CNTT" },
  { ru: "Сайт", vi: "Trang web", pron: "Xait", type: "CNTT" },
  { ru: "Сегодня", vi: "Hôm nay", pron: "Xi-vô-đơ-ni-ya", type: "Trạng từ" },
  { ru: "Завтра", vi: "Ngày mai", pron: "Zát-vơ-ra", type: "Trạng từ" },
  { ru: "Вчера", vi: "Hôm qua", pron: "Vơ-chi-ra", type: "Trạng từ" },
  { ru: "Здесь", vi: "Ở đây", pron: "Zđiê-xi", type: "Trạng từ" },
  { ru: "Там", vi: "Ở kia", pron: "Tam", type: "Trạng từ" },
  { ru: "Сейчас", vi: "Bây giờ", pron: "Xi-chát", type: "Trạng từ" },
  { ru: "Никогда", vi: "Không bao giờ", pron: "Ni-ka-gơ-đa", type: "Trạng từ" },
  { ru: "Огромный", vi: "Khổng lồ", pron: "A-grôm-nưi", type: "Tính từ" },
  { ru: "Безопасный", vi: "An toàn", pron: "Bi-za-pát-nưi", type: "Tính từ" },
  { ru: "Опасный", vi: "Nguy hiểm", pron: "A-pát-nưi", type: "Tính từ" },
  { ru: "Быстрый", vi: "Nhanh", pron: "Bư-xơ-trưi", type: "Tính từ" },
  { ru: "Медленный", vi: "Chậm", pron: "Miê-đơ-liên-nưi", type: "Tính từ" },
  { ru: "Умный", vi: "Thông minh", pron: "Um-nưi", type: "Tính từ" },
  { ru: "Билет", vi: "Vé", pron: "Bi-liết", type: "Danh từ" },
  { ru: "Самолёт", vi: "Máy bay", pron: "Xa-ma-liốt", type: "Danh từ" },
  { ru: "Поезд", vi: "Tàu hỏa", pron: "Pô-iêzt", type: "Danh từ" },
  { ru: "Метро", vi: "Tàu điện ngầm", pron: "Mi-trô", type: "Danh từ" },
  { ru: "Книга", vi: "Sách", pron: "Kơ-ni-ga", type: "Danh từ" },
  { ru: "Ручка", vi: "Bút", pron: "Ruch-ka", type: "Danh từ" },
  { ru: "Тетрадь", vi: "Vở", pron: "Ti-trát", type: "Danh từ" },
  { ru: "Школа", vi: "Trường học", pron: "Xkô-la", type: "Danh từ" },
  { ru: "Ученик", vi: "Học sinh", pron: "U-chi-nik", type: "Danh từ" },
  { ru: "Учитель", vi: "Giáo viên", pron: "U-chi-chiêl", type: "Danh từ" },
  { ru: "Студент", vi: "Sinh viên", pron: "Xtu-điên-t", type: "Danh từ" },
  { ru: "Россия", vi: "Nước Nga", pron: "Ra-xi-ya", type: "Danh từ" },
  { ru: "Вьетнам", vi: "Việt Nam", pron: "Vi-iêt-nam", type: "Danh từ" },
  { ru: "Язык", vi: "Ngôn ngữ", pron: "Ya-zưik", type: "Danh từ" },
  { ru: "Слово", vi: "Từ ngữ", pron: "Xlô-va", type: "Danh từ" },
  { ru: "Погода", vi: "Thời tiết", pron: "Pa-gô-đa", type: "Danh từ" },
  { ru: "Солнце", vi: "Mặt trời", pron: "Xôn-txê", type: "Danh từ" },
  { ru: "Небо", vi: "Bầu trời", pron: "Niê-ba", type: "Danh từ" },
  { ru: "Море", vi: "Biển", pron: "Mô-riê", type: "Danh từ" },
  { ru: "Река", vi: "Sông", pron: "Ri-ka", type: "Danh từ" },
  { ru: "Лес", vi: "Rừng", pron: "Liês", type: "Danh từ" },
  { ru: "Гора", vi: "Núi", pron: "Ga-ra", type: "Danh từ" },
  { ru: "Собака", vi: "Con chó", pron: "Xa-ba-ka", type: "Danh từ" },
  { ru: "Кошка", vi: "Con mèo", pron: "Kôs-ka", type: "Danh từ" },
  { ru: "Машина", vi: "Ô tô", pron: "Ma-xi-na", type: "Danh từ" },
  { ru: "Автобус", vi: "Xe buýt", pron: "Av-tô-bus", type: "Danh từ" },
  { ru: "Хлеб", vi: "Bánh mì", pron: "Khơ-liêp", type: "Thực phẩm" },
  { ru: "Молоко", vi: "Sữa", pron: "Ma-la-kô", type: "Thực phẩm" },
  { ru: "Мясо", vi: "Thịt", pron: "Mi-a-xa", type: "Thực phẩm" },
  { ru: "Яблоко", vi: "Quả táo", pron: "Ya-blă-ka", type: "Thực phẩm" },
  { ru: "Банан", vi: "Quả chuối", pron: "Ba-nan", type: "Thực phẩm" },
  { ru: "Суп", vi: "Súp", pron: "Xup", type: "Thực phẩm" },
  { ru: "Алгоритм", vi: "Thuật toán", pron: "Al-ga-ritm", type: "CNTT" },
  { ru: "Пользователь", vi: "Người dùng", pron: "Pôl-za-va-chel", type: "CNTT" },
  { ru: "Интерфейс", vi: "Giao diện", pron: "In-tiêr-phêis", type: "CNTT" },
  { ru: "Процессор", vi: "Bộ vi xử lý", pron: "Pra-txiê-xơ", type: "CNTT" },
  { ru: "Анализ", vi: "Phân tích", pron: "A-na-liz", type: "CNTT" },
  { ru: "Трафик", vi: "Lưu lượng mạng", pron: "Tra-phik", type: "CNTT" },
  { ru: "Сложный", vi: "Phức tạp", pron: "Xlôz-nưi", type: "Tính từ" },
  { ru: "Простой", vi: "Đơn giản", pron: "Pra-xtôi", type: "Tính từ" },
  { ru: "Интересный", vi: "Thú vị", pron: "In-ti-riê-xnưi", type: "Tính từ" },
  { ru: "Важный", vi: "Quan trọng", pron: "Vaz-nưi", type: "Tính từ" },
  { ru: "Чистый", vi: "Sạch", pron: "Chit-tưi", type: "Tính từ" },
  { ru: "Грязный", vi: "Bẩn", pron: "Gơ-riêz-nưi", type: "Tính từ" },
  { ru: "Паспорт", vi: "Hộ chiếu", pron: "Pát-pôrt", type: "Danh từ" },
  { ru: "Аэропорт", vi: "Sân bay", pron: "A-ê-ra-pôrt", type: "Danh từ" },
  { ru: "Гостиница", vi: "Khách sạn", pron: "Ga-xti-ni-txa", type: "Danh từ" },
  { ru: "Номер", vi: "Số / Phòng", pron: "Nô-miêr", type: "Danh từ" },
  { ru: "Завтрак", vi: "Bữa sáng", pron: "Zát-vơ-răk", type: "Danh từ" },
  { ru: "Обед", vi: "Bữa trưa", pron: "A-biết", type: "Danh từ" },
  { ru: "Ужин", vi: "Bữa tối", pron: "U-zin", type: "Danh từ" },
  { ru: "Врач", vi: "Bác sĩ", pron: "Vrach", type: "Danh từ" },
  { ru: "Помощь", vi: "Sự giúp đỡ", pron: "Pô-môsch", type: "Danh từ" },
  { ru: "Билет", vi: "Vé", pron: "Bi-liết", type: "Danh từ" },
  { ru: "Цена", vi: "Giá cả", pron: "Txiê-na", type: "Danh từ" },
  { ru: "Магазин", vi: "Cửa hàng", pron: "Ma-ga-zin", type: "Danh từ" },
  { ru: "Рынок", vi: "Chợ", pron: "Rư-năk", type: "Danh từ" },
  { ru: "Центр", vi: "Trung tâm", pron: "Txiêntr", type: "Danh từ" },
  { ru: "Улица", vi: "Đường phố", pron: "U-li-txa", type: "Danh từ" },
  { ru: "Площадь", vi: "Quảng trường", pron: "Plô-syát", type: "Danh từ" },
];
